# Generated by Django 5.2.6 on 2025-09-14 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.BigIntegerField(db_index=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='INR', max_length=8)),
                ('provider', models.CharField(max_length=50)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('receipt_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('REQUIRES_ACTION', 'REQUIRES_ACTION'), ('PROCESSING', 'PROCESSING'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED'), ('REFUNDED', 'REFUNDED'), ('PARTIALLY_REFUNDED', 'PARTIALLY_REFUNDED')], default='REQUIRES_ACTION', max_length=32)),
                ('idempotency_key', models.CharField(db_index=True, max_length=64)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['order_id'], name='payments_order_i_b32b33_idx'), models.Index(fields=['provider_payment_id'], name='payments_provide_340c17_idx'), models.Index(fields=['idempotency_key'], name='payments_idempot_1c73ba_idx')],
                'unique_together': {('order_id', 'idempotency_key')},
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('provider_event_id', models.CharField(db_index=True, max_length=128)),
                ('type', models.CharField(max_length=64)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.payment')),
            ],
            options={
                'db_table': 'payment_events',
                'indexes': [models.Index(fields=['provider_event_id'], name='payment_eve_provide_a9c37b_idx'), models.Index(fields=['type'], name='payment_eve_type_483d30_idx')],
                'unique_together': {('payment', 'provider_event_id')},
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('refund_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('REQUESTED', 'REQUESTED'), ('SUCCEEDED', 'SUCCEEDED'), ('FAILED', 'FAILED')], default='REQUESTED', max_length=16)),
                ('provider_refund_id', models.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='payments.payment')),
            ],
            options={
                'db_table': 'refunds',
                'indexes': [models.Index(fields=['provider_refund_id'], name='refunds_provide_22743f_idx')],
            },
        ),
    ]
