# Generated by Django 5.2.6 on 2025-11-02 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_make_transaction_id_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=22, null=True),
        ),
        migrations.CreateModel(
            name='SavedPaymentMethod',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('method_type', models.CharField(choices=[('card', 'Card'), ('upi', 'UPI')], max_length=8)),
                ('token', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=32, null=True)),
                ('last4', models.CharField(blank=True, max_length=4, null=True)),
                ('exp_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('exp_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('masked_display', models.CharField(blank=True, max_length=64, null=True)),
                ('upi_vpa', models.CharField(blank=True, max_length=255, null=True)),
                ('upi_provider_name', models.CharField(blank=True, max_length=64, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('consented', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'saved_payment_methods',
                'indexes': [models.Index(fields=['user_id'], name='saved_payme_user_id_af14b8_idx'), models.Index(fields=['token'], name='saved_payme_token_ee21a2_idx')],
                'unique_together': {('user_id', 'token')},
            },
        ),
    ]
