# Generated by Django 5.2.6 on 2025-11-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_transaction_id_savedpaymentmethod'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='savedpaymentmethod',
            name='saved_payme_token_ee21a2_idx',
        ),
        migrations.AlterUniqueTogether(
            name='savedpaymentmethod',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='card_brand',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='consented',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='exp_month',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='exp_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='masked_display',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='method_type',
            field=models.CharField(choices=[('upi', 'UPI'), ('card', 'CARD')], max_length=16),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='provider',
            field=models.CharField(default='mock', max_length=50),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='upi_provider_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='savedpaymentmethod',
            name='upi_vpa',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddIndex(
            model_name='savedpaymentmethod',
            index=models.Index(fields=['method_type'], name='saved_payme_method__35650e_idx'),
        ),
        migrations.RemoveField(
            model_name='savedpaymentmethod',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='savedpaymentmethod',
            name='updated_at',
        ),
    ]
