# Generated by Django 5.2.6 on 2025-11-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_remove_savedpaymentmethod_saved_payme_token_ee21a2_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedpaymentmethod',
            name='card_holder_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
