# Generated by Django 4.1.7 on 2025-10-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
