# Generated by Django 4.1.7 on 2023-03-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("cart_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.BigIntegerField()),
                ("product_id", models.BigIntegerField()),
                ("quantity", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=20)),
            ],
        ),
    ]
