# Generated by Django 4.1.7 on 2025-10-17 18:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_wishlist_wishlistitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wishlistitems',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='cartitems',
            unique_together={('cart_id', 'product_id')},
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['user_id'], name='cart_cart_user_id_b645f9_idx'),
        ),
        migrations.AddIndex(
            model_name='cartitems',
            index=models.Index(fields=['cart_id', 'product_id'], name='cart_cartit_cart_id_22c4c0_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlist',
            index=models.Index(fields=['user_id'], name='cart_wishli_user_id_bbca57_idx'),
        ),
        migrations.AddIndex(
            model_name='wishlistitems',
            index=models.Index(fields=['wishlist', 'product_id'], name='cart_wishli_wishlis_ef7467_idx'),
        ),
        migrations.AddConstraint(
            model_name='cartitems',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='cartitem_qty_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='wishlistitems',
            constraint=models.CheckConstraint(check=models.Q(('quantity__gte', 1)), name='wishlistitem_qty_gte_1'),
        ),
    ]
