# Generated by Django 4.1.7 on 2025-10-10 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_address_alt_phone_address_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
