# Generated by Django 4.1.7 on 2025-11-01 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_user_user_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pan_card',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
