# Generated by Django 4.1.7 on 2025-08-08 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('value', models.SmallIntegerField(choices=[(-1, 'dislike'), (1, 'like')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='reviewproject.review')),
            ],
            options={
                'ordering': ('-created_at',),
                'unique_together': {('review', 'user_id')},
            },
        ),
    ]
