# Generated by Django 4.1.7 on 2025-08-08 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproject', '0005_review_title_alter_reviewimage_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewImage',
        ),
    ]
