# Generated by Django 4.1.7 on 2025-08-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproject', '0006_delete_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
