# Generated by Django 4.1.7 on 2025-08-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproject', '0009_reviewvideo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewvideo',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='duration_sec',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='hls_master',
            field=models.FileField(blank=True, null=True, upload_to='review_videos/hls/'),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='mp4_faststart',
            field=models.FileField(blank=True, null=True, upload_to='review_videos/mp4/'),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='review_videos/posters/'),
        ),
        migrations.AddField(
            model_name='reviewvideo',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12),
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='video',
            field=models.FileField(upload_to='review_videos/original/'),
        ),
    ]
