# Generated by Django 4.1.7 on 2025-08-25 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewproject', '0010_alter_reviewvideo_options_reviewvideo_duration_sec_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewvideo',
            options={},
        ),
        migrations.RemoveField(
            model_name='reviewvideo',
            name='duration_sec',
        ),
        migrations.RemoveField(
            model_name='reviewvideo',
            name='hls_master',
        ),
        migrations.RemoveField(
            model_name='reviewvideo',
            name='mp4_faststart',
        ),
        migrations.RemoveField(
            model_name='reviewvideo',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='reviewvideo',
            name='status',
        ),
        migrations.AlterField(
            model_name='reviewvideo',
            name='video',
            field=models.FileField(upload_to='review_videos/'),
        ),
    ]
