# Generated by Django 4.1.7 on 2023-03-20 13:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0003_alter_order_total_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="placed_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
