# Generated by Django 4.1.7 on 2023-03-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0004_alter_order_placed_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_id",
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
