# Generated by Django 4.1.7 on 2025-08-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_order_address_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='placed_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
