# Generated by Django 4.1.7 on 2025-10-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_placed_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_code',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
    ]
