# Generated by Django 4.1.7 on 2025-10-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_alter_order_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='product_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id', '-placed_time'], name='order_order_user_id_f9cbd8_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user_id'], name='order_order_user_id_a7f1ea_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-placed_time'], name='order_order_placed__2110ac_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitems',
            index=models.Index(fields=['order_id', 'product_id'], name='order_order_order_i_e16572_idx'),
        ),
    ]
